#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash,
#       ksh, or zsh, you can specify the shell to use by setting the
#       SHELL variable or by uncommenting the line
#       SHELL=/bin/bash
#       below.
#
#   (2) Cygwin / msys / gitbash (:wqis sensitive to the right slash direction.
#       Either use the DOS-style backslash ('\') or forward slash ('/') both
#       are supported - but be aware of some subtle issues (like different
#       named pipes are resolved differently), so don't mix. If you see
#       strange errors below, check that you're not mixing path styles.
#
#    (3) This script is generated from the Gradle template
#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: ´$0´ may be a symlink
app_path="$0"

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -L "$app_path" ]
do
    app_path=$(readlink "$app_path")
    APP_HOME=${app_path%"${app_path##*/}"}
done

APP_HOME=$(cd "${APP_HOME:-.}" && pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
export CLASSPATH="$APP_HOME/lib/gradle-launcher-${GRADLE_VERSION}.jar"

# Use the maximum available, or set MAX_FD != -1 to use that value.
max_fd=$(ulimit -H -n 2>/dev/null || echo 1048576)
if [ -n "$max_fd" ] && [ "$max_fd" != 'unlimited' ]; then
    MAX_FD=$max_fd
else
    MAX_FD="unlimited"
fi

if [ "$OSTYPE" = cygwin ] || [ "$OSTYPE" = msys ] || [ "$OSTYPE" = win32 ] || [ "$OSTYPE" = nativescript ]; then
    # Use the maximum available, or set MAX_FD != -1 to use that value.
    MAX_FD=12000
fi

warn () {
    echo "$*"
} >&2

err () {
    echo "$*"
} >&2

case $OSTYPE in
  solaris* )
    os_name=SunOS
    ;;
  darwin* )
    os_name=Darwin
    ;;
 esac

if [ ! -x "$JAVACMD" ] ; then
    if [ -n "$JAVA_HOME" ] ; then
        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
            # IBM's JDK on AIX uses strange locations for the executables
            JAVACMD="$JAVA_HOME/jre/sh/java"
        else
            JAVACMD="$JAVA_HOME/bin/java"
        fi
    else
        JAVACMD="$(which java)" 2>/dev/null || true
    fi
fi

if [ ! -x "$JAVACMD" ] ; then
    echo "Error: JAVA_HOME is not defined correctly." >&2
    echo "We cannot execute $JAVACMD" >&2
    exit 1
fi

if [ -z "$JAVA_HOME" ] ; then
    echo "Warning: JAVA_HOME environment variable is not set."
fi

JARLOCATION="$APP_HOME/lib/gradle-launcher-${GRADLE_VERSION}.jar"

cd "$APP_HOME" || exit

exec "$JAVACMD" "$@" -jar "$JARLOACTION"
